### ISSUE TITLE
为什么现在 tween.js只有一个参数了

### ISSUE THREAD

**Issue by fangxianzheng** [zhangxinxu/Tween#5]
大神，我看了你的文章，自以为了解了tween.js的原理了。没想到跑去看tween.js。又傻眼了，人家现在方法都只有一个time的参数了，好晕呐，我看了半天还是有点晕。什么时候在讲解讲解啊？

**Comment by zhangxinxu** [comment]
只有一个time是什么意思？没有起止和终止变化量，哪来的动画呢？
