### ISSUE TITLE
toMillisecond这个方法会把如'100m'为转成100000m??

### ISSUE THREAD

**Issue by nancy09** [zhangxinxu/Tween#6]
`
if (/\d+m?s$/.test(obj)) {
  if (/ms/.test(obj)) {
    return 1 * obj.replace('ms', '');
  }
 // 这里还没匹配到‘m’
  return 1000 * obj.replace('s', '');  
}
`

**Comment by zhangxinxu** [comment]
不会，不会进入这个语句。目前只支持 s 和 ms两个单位
